---
- name: Provision VPS
  hosts: provision
  become: true

  tasks:
    - name: Install ca-certificates, gnupg, virtualenv
      apt:
        name: [ca-certificates, gnupg, virtualenv]
        state: present
        update_cache: true
        install_recommends: false

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker.gpg
      register: download_result
      changed_when: download_result.status_code == 200

    - name: Import Docker GPG key
      command:
        cmd: gpg --dearmor -o /etc/apt/keyrings/docker.gpg /tmp/docker.gpg
        creates: /etc/apt/keyrings/docker.gpg

    - name: Set permission for Docker GPG key
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: a+r

    - name: Add Docker APT repository
      shell: >
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg]
        https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" \
        > /etc/apt/sources.list.d/docker.list

    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install Docker packages
      apt:
        name: [docker-ce, docker-ce-cli, containerd.io, docker-buildx-plugin, docker-compose-plugin]
        state: present
        update_cache: true
        install_recommends: false

    - name: Add to Docker group
      user:
        name: tifa
        groups: docker
        append: yes

    - name: Run Docker permissions
      file:
        path: /var/run/docker.sock
        owner: tifa
        group: docker
        mode: 0660

    - name: Install AWS CLI
      apt:
        name: awscli
        state: present
        update_cache: true
        install_recommends: false

    - name: Allow 80/TCP
      ufw:
        rule: allow
        port: "80"
        proto: tcp

    - name: Install make
      apt:
        name: make
        state: present
        update_cache: true
        install_recommends: false
