---
services:

  server:
    image: server:dev
    build:
      context: .
    container_name: server
    hostname: server
    env_file:
      - .env
    labels:
      ansible: true
    restart: always
