---
name: Deploy to production

concurrency: production

"on":
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH configuration
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          ssh-keyscan -p ${{ secrets.REMOTE_PORT }} ${{ secrets.REMOTE_HOST }} \
            >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Push to remote repository
        env:
          GIT_SSH_COMMAND: ssh -i ~/.ssh/key
        run: |
          git fetch --unshallow
          git remote add deploy \
            ssh://${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PORT }}/srv/git/${{ github.event.repository.name }}.git
          git push deploy main -f

      - name: Clean up
        run: |
          rm -rf ~/.ssh
