---
- name: Provision
  hosts: localhost
  gather_facts: false

  roles:
    - config

- import_playbook: server.yaml

- hosts: server
  become: true

  tasks:
    - name: Install packages
      apt:
        name: '{{ item}}'
        state: latest
        update_cache: true
      with_items:
        - gnupg
        - make
        - python3-venv

    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Add user to Docker group
      user:
        name: '{{ ansible_user }}'
        groups: docker
        append: true

    - name: Reset SSH connection to pick up new group
      meta: reset_connection

    - name: Socket file group
      file:
        path: /var/run/docker.sock
        group: docker
        state: file
